config/routes.rb
Rails.application.routes.draw do

	get    'login'   => 'sessions#new'
	post   'login'   => 'sessions#create'
	delete 'logout'  => 'sessions#destroy'

	resources :subscriptions

	root 'homepage#index'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	after_create :create_stripe_customer
	after_update :check_subscription_change
	before_destroy :delete_stripe_customer

	# TODO add validations
	# Can't validate against subscription_choices because view has loads of
	# blank ones, so deal with thos in controller

	validates :first_name, :last_name, :email, :subscription_plan_id, :shipping_day, presence: true
	validates :email, 	presence: true,
			  			uniqueness: true,
			  			format: { with: VALID_EMAIL_REGEX }

	has_many :subscription_choices
	has_many :eliquids, through: :subscription_choices
	has_one :address
	belongs_to :subscription_plan

	accepts_nested_attributes_for :address, allow_destroy: true
	# :subscription_choices currently not required because not nesting
	# in view: subscriptions/new.html.slim
	# accepts_nested_attributes_for :subscription_choices, allow_destroy: true

	def create_stripe_customer
		customer = Stripe::Customer.create(
				card: stripe_token,
				email: email
		)

		self.stripe_customer_id = customer.id

		if initial_ecigarette
			Stripe::InvoiceItem.create(
				customer: customer,
				amount: 2500,
				currency: "gbp",
				description: "E-cigarette kit"
			)
		end

		subscription = customer.subscriptions.create(plan: self.subscription_plan.stripe_plan_id)
		self.stripe_subscription_id = subscription.id

		save!

		send_signup_confirmation
	end
	
	def check_subscription_change
		customer = get_stripe_customer
		subscription = customer.subscriptions.retrieve(self.stripe_subscription_id)
		if subscription.plan.id.to_i != self.subscription_plan.stripe_plan_id
			change_subscription_plan(subscription)
		end
	end
	
	def change_subscription_plan(subscription)
		subscription.plan = self.subscription_plan.stripe_plan_id
		subscription.prorate = false
		subscription.save
	end
	
	def delete_stripe_customer
		customer = get_stripe_customer
		customer.delete
	end

	def send_signup_confirmation
		require 'mandrill'

		message = {
			to: [
					{
							email: self.email,
							name: self.first_name,
					}
			],
			important: false,
			track_opens: true,
			track_clicks: true,
			global_merge_vars: [
					{
							name: 'name',
							content: self.first_name,
					},
			        {
					        name: 'subscription',
					        content: self.subscription_plan.bottle_count_description
			        },
			        {
					        name: 'shipping_date',
			                content: next_shipping_day(get_first_shipping_date)
			        }
			],
		}

		mandrill = Mandrill::API.new ENV['MANDRILL_API']
		sending = mandrill.messages.send_template('signup confirmation', [], message = message)
		
		Rails.logger.info sending
	end


	def check_postcode(subscription, postcode)
		if subscription.address.postcode === postcode
			return true
		end
		false
	end
	
	private
		def get_stripe_customer
			Stripe::Customer.retrieve(self.stripe_customer_id)
		end
	
		def get_first_shipping_date
			today = Date.today
			proposed_shipping_date = Date.new(today.year, today.month, self.shipping_day)
			
			today < proposed_shipping_date ? proposed_shipping_date : today + 1.month
		end
	
		def next_shipping_day(proposed_shipping_date)
			proposed_shipping_date.wday == 0 ? proposed_shipping_date + 1 : proposed_shipping_date 
		end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
	before_action :logged_in_subscription, only: [:show, :edit, :update, :destroy]
	before_action :correct_subscription, only: [:show, :edit, :update, :destroy]

	def show
		@subscription = Subscription.find(params[:id])
	end

	def new
		@subscription = Subscription.new
		@eliquids = Eliquid.all
		@subscription_plans = SubscriptionPlan.all
	end

	def create
		# Assign all the params coming from the view
		@subscription = Subscription.new(subscription_params)
		
		# Set stripe token
		# NB stripe_token is 1 time use only, maybe shouldn't save, should check if it's still in params on model file.
		@subscription.stripe_token = params[:stripeToken]

		if @subscription.save
			# Need to save the subscription before creating subscription choices, same with updating it.
			add_subscription_choices
			log_in @subscription
			flash[:success] = "Welcome to Luxate!"
			redirect_to @subscription
		else
			@eliquids = Eliquid.all
			@subscription_plans = SubscriptionPlan.all
			render 'new'
		end
	end

	def edit
		@subscription = Subscription.find(params[:id])
		@eliquids = Eliquid.all
		@subscription_plans = SubscriptionPlan.all
	end
	
	def update
		@subscription = Subscription.find(params[:id])

		if @subscription.update_attributes(subscription_params)
			@subscription.subscription_choices.destroy_all
			add_subscription_choices
			flash[:success] = "Subscription updated"
			redirect_to @subscription
		else
			@eliquids = Eliquid.all
			@subscription_plans = SubscriptionPlan.all
			render 'edit'
		end
	end
	
	def destroy
		Subscription.find(params[:id]).destroy
		flash[:success] = "Sorry to see you go."
		redirect_to root_path
	end

	private
		def subscription_params
			params.require(:subscription).permit(
				:first_name,
				:last_name,
				:email,
				:subscription_plan_id,
				:shipping_day,
				:initial_ecigarette,
				address_attributes: [
					:house_number,
					:street,
					:second_line,
					:city,
					:county,
					:postcode
				]
			)
		end

		# Iterate over the eliquids array and build a choice for each item
		# A good refactor would be to get rails to do the SQL itself using
		# form_for correctly in the view.
		def add_subscription_choices
			params[:subscription_choices].each do |eliquid_id|
				@subscription.subscription_choices.create(eliquid_id: eliquid_id)
			end
		end

		def logged_in_subscription
			unless logged_in?
				flash[:danger] = "Please log in."
				redirect_to login_url
			end
		end

		def correct_subscription
			@subscription = Subscription.find(params[:id])
			redirect_to(root_url) unless @subscription == current_subscription
		end
	
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper

    # ref: http://www.redguava.com.au/2011/03/rails-3-select-list-items-with-custom-attributes/
    def options_from_collection_for_select_with_attributes(collection, value_method, text_method, data = {}, selected = nil)
        options = collection.map do |element|
            [element.send(text_method), element.send(value_method), data.map do |k, v|
                {"data-#{k}" => element.send(v)}
            end
            ].flatten
        end

        selected, disabled = extract_selected_and_disabled(selected)
        select_deselect = {}
        select_deselect[:selected] = extract_values_from_collection(collection, value_method, selected)
        select_deselect[:disabled] = extract_values_from_collection(collection, value_method, disabled)

        options_for_select(options, select_deselect)
    end
end

app/views/subscriptions/create.html.slim
h1 Subscriptions#create
p Find me in app/views/subscriptions/create.html.slim

app/views/subscriptions/edit.html.slim
.container style="padding-top: 60px;"
	h1 Edit Your Subscription
	= form_for @subscription, html: {role: "form", id: "subscriptionEditForm"} do |subscription_form|
		.row
			= render 'partials/error_messages'
			.col-sm-6.col-sm-offset-3
				h2 Subscription Level
				= subscription_form.select(:subscription_plan_id, options_from_collection_for_select_with_attributes(@subscription_plans, "id", "bottle_count_description", {bottles: "eliquid_count", price: "interval_cost"}, @subscription.subscription_plan.id ), {}, {class: "form-control subscription-plan-select"})
		.row
			.col-sm-6.col-sm-offset-3
				h2 Subscription Cost
				h3.subscription-price = "£#{@subscription.subscription_plan.interval_cost}"
		#subscriptionBox.row
			- @subscription.subscription_choices.each_with_index do |subscription_choice, index|
				- if @subscription.subscription_choices.length == 3
					.col-sm-4.e-liquid-bottle
						= image_tag("eliquid.svg")
						= select_tag("subscription_choices[]", options_from_collection_for_select(@eliquids, 'id', 'name', subscription_choice.eliquid.id), class: "form-control flavour-select")
				- elsif @subscription.subscription_choices.length == 4
					.col-sm-3.e-liquid-bottle
						= image_tag("eliquid.svg")
						= select_tag("subscription_choices[]", options_from_collection_for_select(@eliquids, 'id', 'name', subscription_choice.eliquid.id), class: "form-control flavour-select")
				- elsif @subscription.subscription_choices.length == 5
					- if index == 3
						.col-sm-4.col-sm-offset-2.e-liquid-bottle
							= image_tag("eliquid.svg")
							= select_tag("subscription_choices[]", options_from_collection_for_select(@eliquids, 'id', 'name', subscription_choice.eliquid.id), class: "form-control flavour-select")
					- else
						.col-sm-4.e-liquid-bottle
							= image_tag("eliquid.svg")
							= select_tag("subscription_choices[]", options_from_collection_for_select(@eliquids, 'id', 'name', subscription_choice.eliquid.id), class: "form-control flavour-select")
		.row
			.col-sm-6.col-sm-offset-3
				h2 Shipping Day

				.form-group
					= subscription_form.select :shipping_day, options_for_select(1..31, @subscription.shipping_day), class: "form-control"

		.row
			.col-sm-6.col-sm-offset-3
				h2 Personal Details
				.form-group
					= subscription_form.text_field :first_name, placeholder: "First name*", class: "form-control"
				.form-group
					= subscription_form.text_field :last_name, placeholder: "Last name*", class: "form-control"
				.form-group
					= subscription_form.email_field :email, placeholder: "Email address*", class: "form-control"

		.row
			.col-sm-6.col-sm-offset-3
				= subscription_form.fields_for :address, @subscription.address do |address_form|
					h2 Address
					.form-group
						= address_form.text_field :house_number, placeholder: "House/Flat no.*", class: "form-control"
					.form-group
						= address_form.text_field :street, placeholder: "Street*", class: "form-control"
					.form-group
						= address_form.text_field :second_line, placeholder: "Second line", class: "form-control"
					.form-group
						= address_form.text_field :city, placeholder: "City*", class: "form-control"
					.form-group
						= address_form.text_field :county, placeholder: "County", class: "form-control"
					.form-group
						= address_form.text_field :postcode, placeholder: "Postcode*", class: "form-control"

		.row
			= subscription_form.submit "Save changes", class: "btn btn-default btn-lg"

app/views/subscriptions/new.html.slim
.container#fullPage
	= form_for @subscription, html: {role: "form", id: "subscriptionForm"} do |subscription_form|
		.section
			.container
				= render 'partials/error_messages'

				h2 E-Cigarette
				.question
					h3 Do you require an e-cigarette?
					.radio
						= subscription_form.radio_button(:initial_ecigarette, true)
						= subscription_form.label(:initial_ecigarette_true, "Yes")
					.radio
						= subscription_form.radio_button(:initial_ecigarette, false)
						= subscription_form.label(:initial_ecigarette_false, "No I already have my own e-cigarette. I just require e-liquid.")

		.section
			.container
				.col-sm-6.col-sm-offset-3
					h2 Quantity of E-Liquid
					.tip#quantityTip
						p You need to answer earlier questions first.
					.question#dailyCigarettes.hidden
						h3 How many cigarettes do you smoke a day?
						= subscription_form.select(:subscription_plan_id, options_from_collection_for_select_with_attributes(@subscription_plans, "id", "equivalent_cigarettes_description", {bottles: "eliquid_count", price: "interval_cost"} ), {prompt: "Please select"}, {class: "form-control subscription-plan-select"})
					.question#subscriptionLevel.hidden
						h3 Pick you subscription level.
						= subscription_form.select(:subscription_plan_id, options_from_collection_for_select_with_attributes(@subscription_plans, "id", "bottle_count_description", {bottles: "eliquid_count", price: "interval_cost"} ), {prompt: "Please select"}, {class: "form-control subscription-plan-select"})

		.section
			.container
				h2 Flavours
				.tip#flavoursTip
					p You need to answer earlier questions first.
				.question#preSelectedBottles.hidden
					h4#bottleCount
					p
						| We've gone ahead and picked you out a selection of fantastic flavours to try. Don't worry,
						|  you can change your flavours next month. Or if you want to select your own flavours, 
						a#letMePick click here.

				.question#boxContent.hidden
					h3 Select your flavours

					#subscriptionBox.row
						.col-sm-4.e-liquid-bottle
							= image_tag("eliquid.svg")
							= select_tag("subscription_choices[]", options_from_collection_for_select(@eliquids, 'id', 'name'), { class: "form-control flavour-select" })

				.row.col-xs-12
					button.btn.btn-lg.btn-primary#showMeTheMoney Check out your subscription

		.section
			.container
				.col-xs-8.col-xs-offset-2.one-month
					h2 Price
					.tip#signUpTip
						p Answer all the questions to get a subscription price
					.subscription-offer.hidden
						h3.price
						h3.cigarette-offer
						p.pricing-explanation
						button.btn.btn-lg.btn-primary#signUpButton Sign up
						h4 Upon sign up you will be charged on this day each month.
						h4 Delivery is free. You will be able to select a delivery date.
						h4 You can cancel your subscription at any time.

		.section
			.container
				.col-sm-6.col-sm-offset-3
					h2 Personal Details
					.form-group
						= subscription_form.text_field :first_name, placeholder: "First name*", class: "form-control"
					.form-group
						= subscription_form.text_field :last_name, placeholder: "Last name*", class: "form-control"
					.form-group
						= subscription_form.email_field :email, placeholder: "Email address*", class: "form-control"
					button.btn.btn-lg.btn-primary#enterAddress Enter Address

		.section
			.container
				.col-sm-6.col-sm-offset-3
					= subscription_form.fields_for :address, Address.new do |address_form|
						h2 Address
						.form-group
							= address_form.text_field :house_number, placeholder: "House/Flat no.*", class: "form-control"
						.form-group
							= address_form.text_field :street, placeholder: "Street*", class: "form-control"
						.form-group
							= address_form.text_field :second_line, placeholder: "Second line", class: "form-control"
						.form-group
							= address_form.text_field :city, placeholder: "City*", class: "form-control"
						.form-group
							= address_form.text_field :county, placeholder: "County", class: "form-control"
						.form-group
							= address_form.text_field :postcode, placeholder: "Postcode*", class: "form-control"
					button.btn.btn-lg.btn-primary#selectShippingDay Select Shipping Day
		.section
			.container
				.col-sm-6.col-sm-offset-3
					h2 Shipping Day
					p Which day of the month would you like us to send your subscription.

					.form-group
						= subscription_form.select :shipping_day, options_for_select(1..31), class: "form-control"
					button.btn.btn-lg.btn-primary#enterCardDetails Enter Card Details

		.section
			.container
				.col-sm-6.col-sm-offset-3
					h2 Payment Details
					span.payment-errors
					.form-group
						input.form-control type='text' placeholder='Card Number*' data-stripe='number' size="20"
					.form-group
						input.form-control type='text' placeholder='CVC*' data-stripe='cvc' size="4"
					.form-group
						input.form-control type='text' placeholder='Expiry Month (MM)*' data-stripe='exp-month' size="2"
					.form-group
						input.form-control type='text' placeholder='Expiry Year (YYYY)*' data-stripe='exp-year' size="4"

					= subscription_form.submit "Pay", class: "btn btn-default btn-lg"

	script src='https://js.stripe.com/v2/'

app/views/subscriptions/show.html.slim
.container style="padding-top: 60px;"
	.row
		.col-sm-12.subscription-summary
			h1 Your Subscription
			p
				| Subscription level: 
				= @subscription.subscription_plan.bottle_count_description
			p
				| Monthly cost: £
				= @subscription.subscription_plan.interval_cost

			- @subscription.subscription_choices.each_with_index  do |choice, index|
				- if @subscription.subscription_choices.length == 4
					.col-sm-3.e-liquid-bottle
						= image_tag("eliquid.svg")
						p = choice.eliquid.name
				- else
					- if @subscription.subscription_choices.length == 5 && index == 3

						.col-sm-4.col-sm-offset-2.e-liquid-bottle
							= image_tag("eliquid.svg")
							p = choice.eliquid.name
					- else
						.col-sm-4.e-liquid-bottle
							= image_tag("eliquid.svg")
							p = choice.eliquid.name
	.row
		.col-sm-12.subscription-summary
			p
				| Monthly shipping day: 
				= @subscription.shipping_day

	.row
		.col-sm-2.col-sm-offset-5
			h2 Delivery Address
			.address
				p 
					= @subscription.first_name 
					|  
					= @subscription.last_name
				p 
					= @subscription.address.house_number
					| ,
				p 
					= @subscription.address.street
					| ,
				- if !@subscription.address.second_line.empty?
					p
						= @subscription.address.second_line
						| ,
				p
					= @subscription.address.city
					| ,
				- if !@subscription.address.county.empty?
					p
						= @subscription.address.county
						| ,
				p
					= @subscription.address.postcode
	.row
		.col-sm-12.subscription-summary
			= link_to "Edit Subscription", edit_subscription_path, class: "btn btn-lg btn-primary"
	.row
		.col-sm-12.subscription-summary
			= link_to "Cancel Subscritpion", 
			          subscription_path, 
			          method: 'delete', 
			          data: {confirm: 'Are you sure you want to leave us? This action can\'t be undone.'}, 
			          class: "btn btn-lg btn-danger"